### ISSUE TITLE
Recommender: bit_vector length unmatch error occurred

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#1021]
If ID was deleted between MIX, the following error occurred in ``complete_row_from_id``.
```
[rpc_server.cpp:46] exception in RPC thread: Dynamic exception type: jubatus::core::storage::bit_vector_unmatch_exception::what: calc_hamming_similarity(): bit_vector length unmatch! 128 with 0
```

1. get_diff
2. clear_row(id1)
3. put_diff
4. complete_row_from_id(id1) ==>  ``bit_vector length unmatch!!``

It is an error that should not happen.

**Comment by kmaehashi** [comment]
This issue occurs in the distributed mode in the following scenario:

+ ``update_row(`x`)``
+ ``do_mix()``
+ ``clear_row(`x`)``
+ ``compete_row_from_id(`x`)``

This is because the bit vector whose length is 0 is left in the `diff` table until next MIX.

I reproduced this using the following code:

```
(Console 1) # jubarecommender -z localhost:2181 -n test -p 19199 --interval_sec 0 --interval_count 0
```

```
(Console 2) # jubash
[Jubatus:recommender<>@127.0.0.1:19199] # update_row user1 x 1
[Jubatus:recommender<>@127.0.0.1:19199] # do_mix
[Jubatus:recommender<>@127.0.0.1:19199] # clear_row user1
[Jubatus:recommender<>@127.0.0.1:19199] # similar_row_from_id user1
RPC Error: calc_hamming_similarity(): bit_vector length unmatch! 64 with 0
```

**Comment by kmaehashi** [comment]
This error occurs because APIs like `similar_row_from_id` use erased records in the model.
Currently erased records are expressed as 0-bit `bit_vector` to propagate the row deletion to other servers on MIX.

To fix this situation, we need to discuss how to express such records in the model.  I have following two ideas:

* Fix APIs to ignore all `bit_vector`s in the model whose size is `0`.  Small modification is needed.
* Manage the list of rows erased, separate from the model.  This is a design change including MIX algorithms, so need to be investigated carefully.

**Comment by kmaehashi** [comment]
As discussed in the meeting on 2015-11-30, we decided to go with the former idea:

> * Fix APIs to ignore all bit_vectors in the model whose size is 0. Small modification is needed.

**Comment by kmaehashi** [comment]
This issue only affects to `lsh` and `minhash` algorithms, which use `bit_index_storage`.
`inverted_index` and `euclid_lsh` are no affected.
