### ISSUE TITLE
need support for Delta IDF in global_weight option

### ISSUE THREAD

**Issue by JeffZhang02747** [jubatus/jubatus#1076]
Hi, I am wondering whether is possible to add the "Delta IDF" in the global_weight option.

right now, there is no way to customize the global_weight option.

Delta IDF is useful for classifying two classes.

delta IDF = IDF(in the positive class) - IDF(in the negative class)

The detail of Delta TFIDF is in here:
http://ebiquity.umbc.edu/_file_directory_/papers/446.pdf

**Comment by kumagi** [comment]
In short, it is impossible. But other way may exist.

# structure of `fv_converter`
Jubatus process is consist of two components, `fv_converter` and `driver`.
`global_weight` is managed inside `fv_converter`, it is a functhion which only given `common::datum` and outputs `common::sfv_t`.
`common::datum` is just a kind of JSON of unlabeled data.
`common::sfv_t` is just `vector<pair<string,float> >`.
As you can see, there is no label information given to `fv_converter`.
It is because `fv_converter` is used not only `classifier` but also `recommender`, `anomaly`, `regression` and so on.
 
# other way
IDF calculation is done in `fv_converter`, but there is no reason to prohibit doing it in `classifier`, we can implement special `classifier` inside `driver` which can see label.
